### ISSUE TITLE
Treat 1/1 trains in groups as satisfactory

### ISSUE THREAD

**Issue by hythloday** [mheidal/train-limit-linter#185]
The general principle for FTTL is to have P + D - 1 trains for every P pickup stations and D dropoff stations. This is so there's always a slot to move into, since trains can't transactionally negotiate locks.

But this doesn't quite work when P + D - 1 is 1 - presumably the player is in the middle of setting a route up (let's say they have a production blueprint in place and are waiting for consumers of that blueprint). The train network is "healthy" in a way that it wouldn't be if there were a 2/2 route.

Maybe remove 1/1 groups from the general case of N/N groups, and add an additional checkbox to the Display put them back in?

**Comment by mheidal** [comment]
I don’t understand how P+R-1=1 is a special case. The schedule will only be shown in the schedule report table if any train has that schedule, so if there are too few trains with this schedule then there would be 0 trains and it wouldn’t appear in the schedule, and if there are too many trains with this schedule then the table will recommend that you remove some.

**Comment by hythloday** [comment]
If you have P + R - 0  trains, generally you have a non-functioning train circuit - things can't move from producers to consumers. Removing a train fixes this.
If P + R = 1, you don't have a functioning train circuit whether or not you remove a train. So doing so has no effect (and likely will have to be undone when you place either a P or an R station.

**Comment by mheidal** [comment]
I think I might be misunderstanding you. Do you mean that in a situation where P + R = 1, eg if there is a route from A to B where the limit of A is 1 and the limit of B is 0, then if there’s one train with the schedule A to B the schedule group should be shown as satisfied?
Or do you mean that if P + R = 2, eg there is a route from A to B where the limit of A is 1 and the limit of B is 1, then if there’s one train with the schedule A to B the schedule group should be shown as satisfied? That’s the case already.
If you mean something other than these cases I think an example would be helpful.

**Comment by hythloday** [comment]
Yes, the first example. In my case it also covers a situation (e.g. in SE, though I think it can generally occur) where I've set up production (in SE's case, I've got a landing pad that unloads to a train), but I don't have a receiver station yet.

**Comment by mheidal** [comment]
I think the solution that makes the most sense to me here is a toggle to show/hide schedules with only one station.

**Comment by mheidal** [comment]
I merged this in. If you don't think this solution is satisfactory, please let me know.
