### ISSUE TITLE
Construct additional trains at stations

### ISSUE THREAD

**Issue by hythloday** [mheidal/train-limit-linter#186]
The train construction feature gives you a way of constructing trains, but I think the mod already has enough information to know where to best construct them - at empty stations. Is it considered too automated to put them there?

**Comment by mheidal** [comment]
The way that I personally use it, I have a train deployment area nearby my mall where I can slap down a bunch of new trains as needed. 

Creating new trains (or creating ghost trains) nearby empty train stops which are on the train’s schedule seems like something that could be an option, but it seems a little tricky to do — I’m not sure if you can easily identify what stops are empty, where it’s safe to build a new train, stuff like that. I’ll look into this.
