### ISSUE TITLE
Automate deconstruction of trains

### ISSUE THREAD

**Issue by mheidal** [mheidal/train-limit-linter#188]
This could be done in a few ways:
- Send N trains to a (somehow) marked deconstruction area/station so the player can deconstruct them when they arrive
- Simply mark N trains for deconstruction
- Simply delete N trains from the world (breaks immersion a bit)
This would probably prioritize trains with no cargo in the schedule group. 
This would be a button in a new column in the schedule table, probably.

**Comment by hythloday** [comment]
I'd prefer to see option 2 - I don't have a depot / deconstruction area. I think the priority should be:
1. empty trains not at a station
2. empty trains at
  a. a dropoff station
  b. a pickup station (if these can be distinguished)
3. the train with the least cargo

**Comment by mheidal** [comment]
This would likely be best implemented as a choice by the player between 2 and 3. This would require #201.
It would be useful to ping which train were marked for deconstruction/deleted.
If possible, the script should mark the train for deconstruction "by the player" so that the player can ctrl-Z the deconstruction.
