### ISSUE TITLE
Crash when using older versions of space exploration

### ISSUE THREAD

**Issue by Sil3ntStorm** [mheidal/train-limit-linter#276]
```
Error AppManagerStates.cpp:1659: The mod Train Limit Linter (1.0.32) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event train-limit-linter::on_load()
No such function: space-exploration.get_on_train_teleport_started_event
stack traceback:
[C]: in function 'call'
__train-limit-linter__/scripts/remote_events.lua:37: in function 'handle_remote_events'
__train-limit-linter__/control.lua:620: in function <__train-limit-linter__/control.lua:619>
```

In https://github.com/mheidal/train-limit-linter/blob/main/scripts/remote_events.lua#L35 you are merely checking for the existence of the `space-exploration` remote interface and then assume that it is guaranteed to provide the functions you're calling. This is however not true as those functions only got added to the interface in more recent versions of SE.

Simply adding a check in the form of `if remote.interfaces[se]["function-to-call"] then ... end` should fix this issue.
Of course you might have to add checks elsewhere if you do use those elsewhere without checking for nil.

**Comment by mheidal** [comment]
Thread at https://mods.factorio.com/mod/train-limit-linter/discussion/6680138bf56c02ce4d7df95d
