### ISSUE TITLE
Combine orbits with planets

### ISSUE THREAD

**Issue by Ronoman** [mheidal/train-limit-linter#3]
For Space Exploration (check if enabled). Maybe only do so if there's a space elevator linking the surfaces?

**Comment by mheidal** [comment]
This is difficult to implement, and implementations might obscure other problems.
Space elevators hide the train limit of the station behind them in the schedule, so you can't just assume that P + R - 1 holds if space elevators are discarded.

**Comment by mheidal** [comment]
I don't think that this is workable within the framework of TLL. The fact that trains can't see the train limits of stations which are gated behind a space elevator means that P + R - 1 can't guarantee zero deadlocks.
